services:
  zookeeper-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ZK_CONNECTION_STRING=zookeeper:2181
    volumes:
      - ./protos:/app/protos
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.9
    ports:
      - "2181:2181"
